# Generated by Django 4.2.17 on 2025-01-06 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0004_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactUs',
        ),
    ]
