# Generated by Django 4.2.17 on 2025-01-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0007_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
