# Generated by Django 4.2.17 on 2025-01-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0008_remove_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
