# Generated by Django 4.2.17 on 2025-01-19 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0014_orderitem_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
    ]
