# Generated by Django 4.2.17 on 2025-01-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0015_remove_cartitem_color_remove_orderitem_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(related_name='products', to='ecomm_app.color'),
        ),
    ]
