# Generated by Django 4.2.17 on 2025-01-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0021_alter_color_hex_code_alter_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='products', to='ecomm_app.color'),
        ),
    ]
